//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Stats_2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Project_Stats_2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;Project_Stats_2&lt;/title&gt;
        ///
        ///&lt;script id=&quot;json&quot; type=&quot;text/javascript&quot;&gt;
        ///
        ///var json = &apos;[JSON]&apos;;
        ///var title = &apos;[TITLE]&apos;;
        ///
        ///document.title = title;
        ///
        ///function set_header()
        ///{
        ///	var header = document.createElement(&apos;h2&apos;);
        ///	header.innerHTML = &quot;&lt;b&gt;&lt;u&gt;&quot;+title+&quot; - &quot;+obj.Date+&quot;&lt;/u&gt;&lt;/b&gt;&quot;;
        ///	document.getElementById(&apos;title&apos;).appendChild(header);
        ///}
        ///&lt;/script&gt;
        ///
        ///&lt;script language=&quot;javascript&quot;&gt;
        ///
        ///var charts = [];
        ///var obj = JSON.parse(json);
        ///
        ///var bar_spacing = 32;
        ///
        ///window.onlo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string project_stats {
            get {
                return ResourceManager.GetString("project_stats", resourceCulture);
            }
        }
    }
}
